<?php

namespace PhpLiteCore\View;

use Exception; // Keep for constructor exception
use PhpLiteCore\View\Exceptions\ViewNotFoundException; // Use specific exception

class View
{
    /**
     * The full path to the view file.
     * @var string
     */
    protected string $path;

    /**
     * The data to be passed to the view.
     * @var array
     */
    protected array $data;

    /**
     * View constructor.
     *
     * @param string $view The view file name (e.g., 'home' or 'pages.about').
     * @param array $data The data to make available to the view.
     * @param string $theme The theme to use (optional).
     * @throws ViewNotFoundException If the view file is not found.
     */
    public function __construct(string $view, array $data = [], string $theme = 'default')
    {
        $pathSegments = [
            PHPLITECORE_ROOT,
            'views',
            'themes',
            $theme,
            str_replace('.', DIRECTORY_SEPARATOR, $view) . '.php',
        ];
        $this->path = implode(DIRECTORY_SEPARATOR, $pathSegments);

        if (! file_exists($this->path)) {
            throw new ViewNotFoundException("View file not found: {$this->path}");
        }

        $this->data = $data;
    }

    /**
     * Renders the view and returns the output as a string.
     * Relies on the global error/exception handlers to catch errors within the view file.
     *
     * @return string The rendered view content.
     */
    public function render(): string
    {
        // Extract the data array into individual variables ($pageTitle, $user, etc.)
        // making them directly accessible within the view file.
        extract($this->data);

        // Start output buffering to capture the output generated by the view file.
        ob_start();

        // Include the view file.
        // If any error (Notice, Warning, Fatal) occurs within the view file:
        // 1. set_error_handler will convert it into an ErrorException.
        // 2. The script execution will jump immediately to the exception handler.
        // 3. ob_get_clean() below will NOT be executed in this scope.
        // 4. The global exception handler (set_exception_handler) will take over,
        //    log the error, notify the developer (in production), and display
        //    the appropriate error page (it might clean the buffer itself if needed).
        require $this->path;

        // This line is only reached if the 'require' statement completes successfully
        // without any errors or exceptions.
        return ob_get_clean();
    }

    /**
     * Static factory method for convenience.
     * Creates a new View instance and renders it immediately.
     *
     * @param string $view The view file name.
     * @param array $data The data for the view.
     * @param string $theme The theme to use.
     * @return string
     * @throws ViewNotFoundException
     */
    public static function make(string $view, array $data = [], string $theme = 'default'): string
    {
        // This remains the same, it relies on the corrected render() method.
        return (new self($view, $data, $theme))->render();
    }
}
